### ISSUE TITLE
npm v5.0.3 installation integrity checksum failure

### ISSUE THREAD

**Issue by pluggee** [cncjs/cncjs#172]
I'm trying to install cnc.js on CHIP Pro, ARM based debian. I'm getting an integrity checksum failure, 

~~~~
6967 verbose Linux 4.4.30-pro
6968 verbose argv "/home/chip/.nvm/versions/node/v4.8.3/bin/node" "/home/chip/.nvm/versions/node/v4.8.3/bin/npm" "install" "-g" "cncjs"
6969 verbose node v4.8.3
6970 verbose npm  v5.0.3
6971 error code EINTEGRITY
6972 error sha1-UIwZDsSVggcyOw0+TvzkJ2t65qk= integrity checksum failed when using sha1: wanted sha1-UIwZDsSVggcyOw0+TvzkJ2t65qk= but got sha1-vRS6qdSUXbRUi4Ccv9QD5oPYjHQ=. (327680 bytes)
6973 verbose exit [ 1, true ]
~~~~

I didn't see that when installing on my x64 ubuntu
I've attached the log file for more details
I've seen a couple of posts showing the same failure with npm v5 here

https://github.com/npm/npm/issues/17146
https://github.com/npm/npm/issues/16861

did anyone face that problem?

[2017-06-15T02_34_59_195Z-debug.log.txt](https://github.com/cncjs/cncjs/files/1076446/2017-06-15T02_34_59_195Z-debug.log.txt)

**Comment by pluggee** [comment]
I got the same exact error when installing on a vanilla raspberry pi, running raspbian

[log_rpi.txt](https://github.com/cncjs/cncjs/files/1076843/log_rpi.txt)

**Comment by cheton** [comment]
Try `npm cache verify` or `npm cache --force clean` to make sure everything is consistent.

**Comment by nomykk** [comment]
Getting the same error with current npm version on Windows 10.

**Comment by pluggee** [comment]
tried ~~~~npm cache --force clean~~~~ on both RPi and CHIP, no luck
I also verified that the cache was clean before trying to install

**Comment by olange** [comment]
@pluggee @nomykk Have you tried `npm install --update-binary --no-shrinkwrap`? I had luck with that command, after doing `npm cache clean --force`. And I regenerated and versionned a fresh `npm-shrinkwrap.json` after these operations.

**Comment by pluggee** [comment]
no luck, I tried `npm install --update-binary --no-shrinkwrap cncjs` on rpi

[rpi2.log.txt](https://github.com/cncjs/cncjs/files/1079104/rpi2.log.txt)

**Comment by pluggee** [comment]
@olange @nomykk 
any idea what could be the offending package?

**Comment by olange** [comment]
@pluggee I am not knowledgeable of the internals of NPM, it is as hard for me to point out the offending package, as for you probably.

Looking at your log file and searching for the SHA1 `sha1-UIwZDsSVggcyOw0+TvzkJ2t65qk=` that fails, I found these lines:

```
6198 silly pacote trying cncjs@https://registry.npmjs.org/cncjs/-/cncjs-1.9.5.tgz by hash: sha1-UIwZDsSVggcyOw0+TvzkJ2t65qk=
6199 silly extract webappengine@1.1.3
6200 silly pacote trying webappengine@https://registry.npmjs.org/webappengine/-/webappengine-1.1.3.tgz by hash: sha1-/OuwAQBhqKSDzgYdtVRPLRDxskI=
6201 silly pacote data for sha1-UIwZDsSVggcyOw0+TvzkJ2t65qk= not present. Using manifest.
6202 silly pacote data for sha1-/OuwAQBhqKSDzgYdtVRPLRDxskI= not present. Using manifest.
```

It is however unclear to me what to start with these lines.

**Comment by cheton** [comment]
No sure what's going wrong. Try manually removing `~/.npm` and previously installed cncjs if you have, and then install again:
```
$ rm -rf ~/.npm
$ npm uninstall -g cncjs
$ npm cache verify
$ npm install -g cncjs@latest
```

**Comment by nomykk** [comment]
@pluggee  @olange 
Deleting the cache manually from path "C:\Users\user-name\AppData\Roaming" (directories: npm , npm-cache) worked for me. After deleting directories npm install did the rest accurately.

**Comment by nuintun** [comment]
same problem, no ```package-lock.json```
 
![_20170622160717](https://user-images.githubusercontent.com/1730277/27423793-66518414-5765-11e7-95d0-bc33a9883189.png)

**Comment by pluggee** [comment]
hey @cheton , I tried removing `~/.npm` and following your instructions, still the same problem
I have really no knowledge of npm (other that following instructions), did anyone try to install cncjs on a vanilla raspbian (released 2017-04-10)?
I followed instructions on a tiny intel box running ubuntu 16.04 and it went through, I only faced this problem with 2 systems running ARM cores, Raspberry Pi running Raspbian and C.H.I.P. Pro running debian

**Comment by pluggee** [comment]
any other ideas??

**Comment by anosikeosifo** [comment]
The following solved it for me: 

rm -rf ~/.npm
npm install --update-binary --no-shrinkwrap

*O.S: MacOS 10.12.5
 NPM 5.0.4

**Comment by SumeethPrabhakar** [comment]
I deleted the npm cache (folders npm , npm-cache) manually from path "C:\Users\user-name\AppData\Roaming". worked for me.

**Comment by taylorstine** [comment]
I fixed this by running:

```
gpg --keyserver pool.sks-keyservers.net --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
gpg --keyserver pool.sks-keyservers.net --recv-keys FD3A5288F042B6850C66B31F09FE44734EB7990E
gpg --keyserver pool.sks-keyservers.net --recv-keys 71DCFD284A79C3B38668286BC97EC7A07EDE3FC1
gpg --keyserver pool.sks-keyservers.net --recv-keys DD8F2338BAE7501E3DD5AC78C273792F7D83545D
gpg --keyserver pool.sks-keyservers.net --recv-keys C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8
gpg --keyserver pool.sks-keyservers.net --recv-keys B9AE9905FFD7803F25714661B63B535A4C206CA9
gpg --keyserver pool.sks-keyservers.net --recv-keys 56730D5401028683275BD23C23EFEFE93C4CFFFE
curl -O https://nodejs.org/dist/v8.1.4/SHASUMS256.txt.asc
gpg --verify SHASUMS256.txt.asc
```

I'll be honest I'm not totally sure what it does (something with key signing obviously).  I got this from the README included with the [node binary downloads](https://nodejs.org/dist/v8.1.4/node-v8.1.4-linux-x64.tar.xz).

**Comment by Ankit14190Pinal** [comment]
I got error when I installing angular "npm install -g @angular/cli"

I removed @angular and @angular-cli from npm-cache 'C:\Users\Engraved\AppData\Roaming\npm-cache'
now it's working for me.

**Comment by StavroMueller** [comment]
Was getting this error, but in my case it was fixed by first running `npm cache clean`, even though the output scolded me a bit.

**Comment by liliom55** [comment]
Still get error with npm version 5.3.0
`npm ERR! code EINTEGRITY
npm ERR! sha1-mnHEh0chjrylHlGmbaaCA4zct78= integrity checksum failed when using sha1: wanted sha1-mnHEh0chjrylHlGmbaaCA4zc
t78= but got sha1-BdAljdQ4f3upWYe2eNqgFyKwnWE=. (4849289 bytes)`

**Comment by hezhiwebworld** [comment]
npm ERR! sha512-vOk6uEMctu0vQrvuSqFdJyqj1Q0S5VTDL79qtjo+DhRr+1mmaD+tluFSCZqhvi/J
UhXSzoZN2BhtstaPEeE8cw== integrity checksum failed when using sha512: wanted sha
512-vOk6uEMctu0vQrvuSqFdJyqj1Q0S5VTDL79qtjo+DhRr+1mmaD+tluFSCZqhvi/JUhXSzoZN2Bht
staPEeE8cw== but got sha512-pd+s9UiGqI1iFyuo9HnBrpGNNOE1o0VThHvIcRX0ECoMjQkINlVo
PG4MNzp4eyTVcvRieTaIEt35aB5PCU+NuA==. (2233 bytes)


npm  更新之后就是这么的坑爹

**Comment by pluggee** [comment]
@taylorstine I tried adding and verifying the keys, but still no luck, I'm getting the same error

**Comment by AustinSaintAubin** [comment]
what is your `node -v` and `npm -v` ?

**Comment by pluggee** [comment]
@AustinSaintAubin 
npm -v = 5.0.3
there's an update available to 5.3.0
node -v = v4.8.3

**Comment by AustinSaintAubin** [comment]
Try updating to node v6.

**Comment by cheton** [comment]
@pluggee 

Try `npm i -g npm@latest` to update NPM to the latest version (5.3.0), and clean npm cache again before installation. I'm not sure if the checksum error can be resolved with the latest NPM, hope it works for you.

**Comment by Enamex** [comment]
[**@cheton**](https://github.com/cheton) commented on [Aug 14, 2017, 4:36 AM GMT+2](https://github.com/cncjs/cncjs/issues/172#issuecomment-322087486 "2017-08-14T02:36:02Z - Replied by Github Reply Comments"):
> [@pluggee](https://github.com/pluggee)
> 
> Try `npm i -g npm@latest` to update NPM to the latest version (5.3.0), and clean npm cache again before installation. I'm not sure if the checksum error can be resolved with the latest NPM, hope it works for you.

Doing this was the first time I noticed this error, actually.

So I can't update npm. On 5.0.3 right now.

**Comment by onuar** [comment]
@cheton npm 5.3.0 still has the same problem.

**Comment by gezzeg** [comment]
also have same problem here on fresh installation.

Try "npm cache --force clean" but no luck.

Then i remove project folder and reinstall. Luckily some how it works!.

![screen shot 2017-08-27 at 10 11 03 pm](https://user-images.githubusercontent.com/876838/29750605-161b6c3c-8b75-11e7-93a2-6960152b8b13.png)

**Comment by OrionStark** [comment]
BTW, I try to downgrade the npm version to npm@4.6.1 and it's doing well.

**Comment by cheton** [comment]
NPM v5 is still unstable and existed some [known issues](https://github.com/npm/npm/issues/16991), for anyone who encountered installation problems with npm v5, try to downgrade the npm version to npm@4.6.1, clean npm cache, and continue the installation:

```sh
npm i -g npm@4.6.1
rm -rf ~/.npm
```

Each time you do the installation, you can run `npm cache verify` to verify the npm cache:
```sh
npm cache verify
npm install -g cncjs@latest # or 'sudo npm install --unsafe-perm -g cncjs@latest' for root account
```

Note: Do not install cncjs in a project folder containing a package.json file, Install cncjs globally with the `-g` option, or it may cause unexpected result.

**Comment by aliir74** [comment]
My problem solved with @taylorstine solution.
node version: 8.4.0
npm version: 5.4.0

**Comment by AbhilashDawar** [comment]
Updated to the latest versions as mentioned by @aliir74 i.e.
node version: 8.4.0
npm version: 5.4.0
Then ran command prompt as administrator. It worked.

**Comment by DeltaCap019** [comment]
@cheton solution worked for me.. make sure you **Quit** the terminal in mac first, before implementing this solution

**Comment by ParnianKamran** [comment]
I had the same issue and I used all the above solutions but they did not work for me. Please try Uninstalling node and npm and delete npm and npm-cache manually and again install node (Latest LTS Version: v6.11.3 (includes npm 3.10.10)) and npm and I hope that it works for you too.

**Comment by onuar** [comment]
Since I've upgraded npm to '5.4.1' version, I don't encounter this error.

**Comment by ParnianKamran** [comment]
@onuar I also upgraded npm to 5.4.1 version but it did not work, maybe my solution could be the last one if the above solutions did not work

**Comment by cheton** [comment]
Seems to be resolved in NPM 5.4.0. Does anyone still have failure with NPM 5.4.0?

**Comment by andy-ex** [comment]
Had the same problem, upgraded to NPM 5.4.0 and installation was successful. Thanks @cheton !

**Comment by cheton** [comment]
Can someone help create a new section in the [Troubleshooting](https://github.com/cncjs/cncjs/wiki/Troubleshooting) page for how to resolve the installation problem? That will save a lot of trouble and time for people who also encountered similar errors with NPM installation. 

https://github.com/cncjs/cncjs/wiki/Troubleshooting

**Comment by srsgores** [comment]
For me, I uninstalled nodejs and then reinstalled.  Problem solved, even with `npm@5.3.0`

**Comment by pluggee** [comment]
@cheton , alright, seems to be fixed now if I follow vanilla instructions, when running `npm install npm@latest -g` it installs npm 5.4.2 and that solves the issue. I've successfully installed cncjs on a RPi 3 and RPi zero W
thanks for your support!

**Comment by Arafullahi** [comment]
try `npm i -g npm `
and `npm cache verify`

**Comment by tangjia0902** [comment]
@hezhiwebworld 
Seems I met same error as you when run "npm install":
npm ERR! sha512-N9OVsMBspboNvYaLAQnLEhb2eQ96lavogMR5LoH5k8nb1PvBZHSBFhzhsq2LNzGTBBOtBviOc1GiSu+wlM/pGw== integrity checksum failed when using sha512: wanted sha512-N9OVsMBspboNvYaLAQnLEhb2eQ96lavogMR5LoH5k8nb1PvBZHSBFhzhsq2LNzGTBBOtBviOc1GiSu+wlM/pGw== but got sha512-vXVO4mBnzw63SlWWii6j7K54a+HFrqc+fA4svOVWqVBTUaw8+rys3JClRchoD8EPCBAq0D9kJpEb+gRndZbhxQ==. (5518 bytes)

Did you fix the error?

**Comment by cheton** [comment]
@tangjia0902 

What's your npm version?

**Comment by tangjia0902** [comment]
@cheton 
npm version: 
npm: '5.3.0'

**Comment by cheton** [comment]
Try the following:

```sh
npm i -g npm
rm -rf ~/.npm
npm cache verify  # optional
```

**Comment by zibraque** [comment]
@tangjia0902  me too . did you fixed it yet?
@cheton  it's not working at all , npm --version 5.3.0 || windows10 wamp
```
################> npm i -g npm
npm ERR! code EINTEGRITY
npm ERR! sha512-M3aO8EjHebaCw6uur4C86SZqkypnoaEVo5R63FEEU0dw9wLxf/JlwWtJItShYVyQS2WDxG2It10GEe5GmVEM2Q== integrity checksum failed when using sha512: wanted sha512-M3aO8EjHebaCw6uur4C86SZqkypnoaEVo5R63FEEU0dw9wLxf/JlwWtJItShYVyQS2WDxG2It10GEe5GmVEM2Q== but got sha512-E0Xl+HGfFiPpkiHI05tsCo2vgRcqTsM2Gh3Ul1uHScGzR7PggUChr2i6Ql3z571LBKzs3eTm00fEoORJIETrLw==. (1703936 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2017-11-14T01_45_09_893Z-debug.log
```

**Comment by cheton** [comment]
Have you tried removing the npm cache folder "C:\Users\admin\AppData\Roaming\npm-cache\" on Windows?

**Comment by zibraque** [comment]
@cheton  I solved it by reloaded node.js . Tks anyway

**Comment by tangjia0902** [comment]
@cheton @zibraque 
Finally, I solved it by config .npmrc to "registry = https://registry.npm.taobao.org"
Thanks all.

**Comment by satishGangineni** [comment]
deleting the npm and npm cache folders from C:\Users\<user>\AppData\Roaming the path works for me!

**Comment by BhuvaneswariVajravel** [comment]
Hi i got the same issue in windows
my versions are bellow
node -v
8.9.1
npm -v
5.4.0

i removed npm and npm-caches from AppData/Roaming


but when i try to >npm install -g @angular/cli@latest


i got the following EINTEGRITY error


> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\@an
> gular\cli\node_modules\fsevents):
> npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: Cannot cd into 'C:\Users\b
> huvaneswari_v\AppData\Roaming\npm\node_modules\.staging\fsevents-a025fdf0'
> 
> npm ERR! code EINTEGRITY
> npm ERR! sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= integrity checksum failed when using
> sha1: wanted sha1-PFtv1/beCRQmkCfwPAlGdY92c6Q= but got sha1-JsYlG6Gk8MTk+61T/R9R
> DoCk/QU=. (1024615 bytes)
> npm WARN tar ENOENT: no such file or directory, open 'C:\Users\bhuvaneswari_v\Ap
> pData\Roaming\npm\node_modules\.staging\rxjs-87a55af1\_esm2015\testing\TestSched
> uler.js.map'
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\bhuvaneswari_v\AppData\Roaming\npm-cache\_logs\2017-12-05T
> 07_52_25_588Z-debug.log
> 
> C:\>npm -v
> 5.4.0
> 
> C:\>node-v
> 'node-v' is not recognized as an internal or external command,
> operable program or batch file.
> 



please anyone help me

**Comment by johnlin0207** [comment]
I updated my npm from 5.0.3 to 5.6.0,it seems worked!

**Comment by AlexanderMac** [comment]
Completely removed node (I use nvm). And reinstalled it.

**Comment by jonnycraze** [comment]
After going through much of what worked for others above I ended up removing my package-lock file, and that fixed it for me.

**Comment by rodrigoengelberg** [comment]
The following solved it for me:
rm -rf node_modules
rm package-lock.json
rm -rf ~/.npm
npm install --update-binary --no-shrinkwrap

**Comment by samfrach** [comment]
nothing worked for me on windows 10... but when I run "cmd" as Administrator... everything worked :)

**Comment by bjmckenz** [comment]
Unsubscribe

On March 2, 2018 11:19:49 AM PST, Matthew Watts <notifications@github.com> wrote:
>"npm cache verify" fixed the issue for me. Output says "Corrupted
>content removed: 23"
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cncjs/cncjs/issues/172#issuecomment-370024706

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by KEMBL** [comment]
"integrity checksum failure"
it happened with me when I changed my own npm server version from Sinopia to Verdaccio and copied packages to the new repo and then tried to use them. So be aware of such a case.

**Comment by ptusch** [comment]
@KEMBL Did you actually fix this? Stuck at the same thing right now. :s

**Comment by demetrioin** [comment]
I had exactly the same issue. I fixed by commenting in .npmrc my registry (//registry=https://artifactory.MYCOMPANY.net/artifactory/api/npm/releases_npm_all/) and using a network without proxy

**Comment by janeyzou** [comment]
i deleted npm-cache.And i tryed to npm i -g npm
and npm cache verify,,but it's not to worked
npm version:
npm: '6.4.1'
node version
node 8.11.1
![20180912194804](https://user-images.githubusercontent.com/29591600/45423231-40fdfd80-b6c5-11e8-9ef5-8cd60ea26267.png)

**Comment by AustinSaintAubin** [comment]
@janeyzou install Node v10

# Remove Old Packages (Optional)
###sudo apt-get purge -y npm nodejs
###sudo apt-get autoremove -y

curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -  # Install NodeJS v10
sudo apt-get install -y nodejs ## npm  ## npm nodejs-legacy #(Installed with nodesource)

————

Also, I am working on a raspberry pi image currently. I hope to have it published in the following week.
See the notes on it here:
https://github.com/cncjs/cncjs-pi-raspbian/blob/master/%23NOTES.md

**Comment by patilharshal16** [comment]
> The following solved it for me:
> rm -rf node_modules
> rm package-lock.json
> rm -rf ~/.npm
> npm install --update-binary --no-shrinkwrap
> 
> *O.S: MacOS 10.12.5
> NPM 5.0.4

This works for me. Removing existing dependencies help.

**Comment by Kiee** [comment]
I'm getting this issue when I am trying to install `node-sass`

npm -v
6.9.0

node -v
v10.16.0


Command:

`$ npm install node-sass -g
npm ERR! code EINTEGRITY
npm ERR! sha512-3g8lYefrRRzvGeSowdJKAKyks8oUpLEd/DyPV4eMhVlhJ0aNaZqIrNUIPuEWWTAoPqyFkfGrM67MC69baqn6vA== integrity checksum failed when using sha512: wanted sha512-3g8lYefrRRzvGeSowdJKAKyks8oUpLEd/DyPV4eMhVlhJ0aNaZqIrNUIPuEWWTAoPqyFkfGrM67MC69baqn6vA== but got sha512-jIvvQweolCmipqZXjsC8NUIKS/iux7/bKsBBZQCCMibvCg/eNyz0L7L7ddO9r1dRStqWyBlrHFUPRrF56wCr/A==. (2121 bytes)
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry
npm WARN tar invalid entry

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\la17\AppData\Roaming\npm-cache\_logs\2019-07-08T12_00_04_526Z-debug.log`

I have tried

- npm cache --force clean
- npm cache verify
- npm i npm -g
- Deleting npm & npm-cache folders from C:\Users\User\AppData

Other notes, I am working on a corporate proxy. I have `http_proxy` and `https_proxy` config variables set, I have not had an issue with this before.
I have tried setting the config `strict-ssl=false`
I have also exported my companies content inspection self signed certificates and set cafile config to this.

This is a global install so I cannot find a package-lock.json file to delete.

uninstalled and reinstalled nodejs and npm.

Out of ideas.

**Comment by Karishma1208** [comment]
npm ERR! Unexpected end of JSON input while parsing near '...":{"integrity":"sha51'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-05-04T06_43_14_158Z-debug.log
how to solve this error

**Comment by bensalcie** [comment]
On my side, i closed VS code, run terminal as admin, cd into the app folder then 
run code .
 npm cache --force clean 
and it worked
